export const ActionTypes = {
    SET_EMPLOYEE : 'SET_EMPLOYEE',
    SELECTED_EMPLOYEE : 'SELECTED_EMPLOYEE',
    REMOVE_SELECTED_EMPLOYEE : 'REMOVE_SELECTED_EMPLOYEE',
    UPDATE_EMP : 'UPDATE_EMP',
    ADD_EMPLOYEE : 'ADD_EMPLOYEE',
    DELETE_EMPLOYEE : 'DELETE_EMPLOYEE'
    
}